(* @04: Failure in an instruction. *)
          open Kot.Deque;;
(* @01 *) let x0 = empty;;
          let x1 = x0;;
(* @02 *) let x1 = inject x1 1;;
          let x1 = inject x1 2;;
          let x1 = inject x1 3;;
          let x1 = inject x1 4;;
          let x1 = inject x1 5;;
          let x1 = inject x1 6;;
          let x1 = inject x1 7;;
          let x1 = inject x1 8;;
          let x1 = inject x1 9;;
(* @03 *) let x2 = concat x1 x1;;
          let x3 = x2;;
(* @04 *) let x3, e = eject x3;;
          let x3, e = eject x3;;
          let x3, e = eject x3;;
          let x3, e = eject x3;;
          let x3, e = eject x3;;
          let x3, e = eject x3;;
          let () = check x3;;
